name: Deploy to GitHub Pages
env:
  PUBLISH_DIR: bin/Release/netstandard2.1/publish/wwwroot
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v2
      
      - name: Update .NET SDK
        uses: martincostello/update-dotnet-sdk@v1.1.0
        with:
          # The optional .NET release channel to download the SDK for (2.1, 3.1, 5.0, etc.).
          channel: 5.0
      
        
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish -c Release
        
      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: /LeoGResume/
        
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

